<a href="https://colab.research.google.com/github/NeoBro34/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

2.2.2

In [3]:
mydataset = {
    'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Ford', 'BMW'],
    'counts': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [6]:
df.head(6) # default 5 rows  boshidan boshlab datalarni olish mumkin

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9

In [7]:
df.tail() # defaul 5 rows  / oxiridan boshlab datalarni olish mumkin

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [8]:
df.shape  # datalarimizning qator ustunlarini aniqlab beradi

(7, 2)

In [10]:
df.columns  # datalarimizning columlarini hamda data typeni aniqlab beradi

Index(['cars', 'counts'], dtype='object')

In [11]:
df.dtypes  # typlarini aniqlashda yordamga keladi

cars      object
counts     int64
dtype: object

In [12]:
df.describe() # numerical columns only.  (includes='all)

         counts
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [15]:
df.iloc[3:]  # datani select qilishda yordamga keladi  [1:4] <- bunaqa yozishimiz ham mumkin

      cars  counts
3    Tesla       8
4  Ferrari       1
5     Ford       9
6      BMW       3

In [16]:
df.loc[:, 'counts']  # bizga kerakli columlarning datalarini olish imkonini beradi / [2, 'cars'] | [2:5, 'cars']...

0    3
1    7
2    2
3    8
4    1
5    9
6    3
Name: counts, dtype: int64

In [18]:
df[df['counts'] > 3]  # xoxlagan conditionlardan foydalanib datalarni fetch qilishimiz mumkin

    cars  counts
1  Volvo       7
3  Tesla       8
5   Ford       9

In [19]:
df[df['cars'] == 'BMW']

  cars  counts
0  BMW       3
6  BMW       3

In [22]:
df.mean(numeric_only=True)  # numericlarning o'rtacha miqdorini hisoblab beradi

counts    4.714286
dtype: float64

In [23]:
df['counts'].mean()

np.float64(4.714285714285714)

In [24]:
df.sum()

cars      BMWVolvoFordTeslaFerrariFordBMW
counts                                 33
dtype: object

In [25]:
df.min()

cars      BMW
counts      1
dtype: object

In [26]:
df.max()

cars      Volvo
counts        9
dtype: object

In [27]:
df.median(numeric_only=True)  # midium value

counts    3.0
dtype: float64

In [28]:
df.count()

cars      7
counts    7
dtype: int64

In [29]:
df.std(numeric_only=True)  # standart deviation

counts    3.199702
dtype: float64

In [30]:
data_widh_missing = {
    'cars': ['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford'],
    'counts': [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_widh_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [31]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [32]:
df_missing.dropna()

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [33]:
df_missing.dropna(how='all') # buyerda qay birida ma'lumot bo'lsa bas olib beradi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [34]:
df_missing.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [35]:
df_missing.dropna(subset=['cars'])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [37]:
df_missing.fillna({'cars': 'unknown', 'counts': 0})  # bo'sh datasetlarni to'ldirish

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [40]:
# haqiqiy datalarni o'qish =============================================================================

df = pd.read_csv('Titanic-Dataset.csv')
df.head(10)

# df = pd.read_excel('Titanic-Dataset.xlsx')
# df = pd.read_json('Titanic-Dataset.json')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [41]:
df.to_excel('output.xlsx')

In [43]:
df = pd.read_excel('output.xlsx')
df.tail(3)

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [44]:
# Series => 1D.    ============================================================================================
cars = pd.Series(['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Ford', 'BMW'])
print(cars)

0        BMW
1      Volvo
2       Ford
3      Tesla
4    Ferrari
5       Ford
6        BMW
dtype: object

In [45]:
cars_series = data_widh_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']